package grupo8

import grupo8.*;
import robocode.*;
import robocode.ScannedRobotEvent;

query "consulta_acciones"
  accion: Accion()
end

rule "sin robots a la vista -> giro completo del radar"
   when
      not (exists ScannedRobotEvent())
   then
      insert (new Accion(Accion.GIRAR_RADAR_DER, 360, 1));
      System.out.println("one");
end

rule "FOGO no inimigo e anda"
   when
      $status : EstadoRobot()
      ScannedRobotEvent($nombre: name, $angulo: bearing)
      not (eval($nombre.contains("Dilmae")))
      not (eval($nombre.contains("FaustoSilva")))
   then
      double anguloRelativoCanon = Auxiliar.anguloRelativo($status.getHeading(), $status.getGunHeading()); 
   	  insert(new Accion(Accion.GIRAR_CANON_DER, ($angulo-anguloRelativoCanon), 1));
	  insert(new Accion(Accion.DISPARAR, Math.min(Rules.MAX_BULLET_POWER, 0.10*$status.getEnergy()), 1));
end

rule "choque"
when
   HitRobotEvent()
then
   insert(new Accion(Accion.RETROCEDER, 100, 5));
end


rule "choque con muro"
when
   HitWallEvent($anguloRelativo: bearing)
then
   insert(new Accion(Accion.GIRAR_TANQUE_DER, (- $anguloRelativo), 5));
   insert(new Accion(Accion.AVANZAR, 100, 5));
end
